# Generated by Django 3.2.9 on 2021-12-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_api', '0002_alter_timer_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='begin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timer',
            name='end',
            field=models.DateTimeField(),
        ),
    ]
